openapi: '3.0.3'

info:
  title: 'gowiki API'
  version: '0.0.1'

servers:
  - url: 'http://localhost:9000/'
    description: 'API Server'

paths:
  '/healthcheck':
    get:
      responses:
        '200':
          description: 'OK'
        default:
          $ref: '#/components/responses/UnexpectedError'
      security: []
  '/privatecheck':
    get:
      responses:
        '200':
          description: 'Auth OK, this is private # TODO'
      security:
        - cookieAuth: []
  '/users':
    post:
      requestBody:
        description: 'signup(username, password) 2 <= username.len() <= 20, 2 <= password.len() <= 50, regex '
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              username: 'Bob'
              password: 'pass'
      responses:
        '200':
          description: 'signup'
      security: []
  '/login':
    post:
      requestBody:
        description: 'login'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              username: 'Bob'
              password: 'pass'
      responses:
        '200':
          description: 'login success'
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - username
                  - message
                properties:
                  status:
                    type: integer
                  username:
                    type: string
                  message:
                    type: string
              example:
                status: 200
                username: 'Bob'
                message: 'login ok'
    delete:
      responses:
        '200':
          description: 'logout'
      security: []
  '/groups':
    get:
      responses:
        '200':
          description: 'userの入っているgroupを返却する'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGroups'
              example:
                user_groups:
                  - 'suburi-dev'
                  - 'public'
                  - 'myPrivate'
      security:
        - cookieAuth: []

    post:
      requestBody:
        description: 'postでgroup作成、deleteは後で作る(deleteでgroup削除)'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
            example:
              group_name: 'Bobs_group'
              group_members:
                - "Bob"
                - "Nancy"

      responses:
        '200':
          description: 'group作成'
          content:
            application/json:
              schema:
                type: object
                required:
                  - group_name
                properties:
                  group_name:
                    type: string
              example:
                group_name: 'Bobs_group'
      security:
        - cookieAuth: []

# TODO /groups/:group_name グループにmemberを追加/削除できるようにする

components:
  schemas:
    Error:
      description: 'Error'
      type: object
      required:
        - message
        - code
      properties:
        message:
          title: 'error message'
          type: string
          example: 'unexpected error'
        code:
          title: 'status code'
          type: integer
          minimum: 100
          maximum: 600
          example: 500
    User:
      description: 'username/password'
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    Group:
      description: 'group articleの公開範囲をグループ単位にする'
      type: object
      required:
        - group_name
      properties:
        group_name:
          type: string
        group_members:
          type: array
          items:
            type: string
    UserGroups:
      description: 'ユーザが所属するグループ一覧'
      type: object
      required:
        - user_groups
      properties:
        user_groups:
          type: array
          items:
            type: string
  responses:
    OK:
      description: 'ok'
    UnexpectedError:
      description: 'unexpected error'
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSIONID
